/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockL2StandardBridgeSol from "./MockL2StandardBridge.sol";
export type { mockL2StandardBridgeSol };
export type { MockERC20 } from "./MockERC20";
