/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMockL2StandardBridge__factory } from "./IMockL2StandardBridge__factory";
export { MockL2StandardBridge__factory } from "./MockL2StandardBridge__factory";
