/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IL2StandardBridge,
  IL2StandardBridgeInterface,
} from "../../../contracts/SchnellFundSender.sol/IL2StandardBridge";

const _abi = [
  {
    inputs: [],
    name: "messenger",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_l2Token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_minGasLimit",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "_extraData",
        type: "bytes",
      },
    ],
    name: "withdrawTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IL2StandardBridge__factory {
  static readonly abi = _abi;
  static createInterface(): IL2StandardBridgeInterface {
    return new Interface(_abi) as IL2StandardBridgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IL2StandardBridge {
    return new Contract(address, _abi, runner) as unknown as IL2StandardBridge;
  }
}
