/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IL2StandardBridge__factory } from "./IL2StandardBridge__factory";
export { SchnellFundSender__factory } from "./SchnellFundSender__factory";
