/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMockL2StandardBridge } from "./IMockL2StandardBridge";
export type { MockL2StandardBridge } from "./MockL2StandardBridge";
