/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockL2StandardBridgeSol from "./MockL2StandardBridge.sol";
export { MockERC20__factory } from "./MockERC20__factory";
