/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IL2StandardBridge } from "./IL2StandardBridge";
export type { SchnellFundSender } from "./SchnellFundSender";
