/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as schnellFundSenderSol from "./SchnellFundSender.sol";
export type { schnellFundSenderSol };
import type * as test from "./test";
export type { test };
